version: "3"
services:
  back_app:
    restart: unless-stopped
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - environment/.env.${NODE_ENV:-development} # configure postgres
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: mongo:latest # use latest official mongodb version
    env_file:
      - environment/.env.${NODE_ENV:-development} # configure postgres
    volumes:
      - database-data:/data/db # persist data even if container shuts down
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  database-data:
