version: "3"
services:
  back_app:
    restart: unless-stopped
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - environment/.env.${NODE_ENV:-development} # configure postgres
    networks:
      - app-network
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:5.0 # use latest official mongodb version
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: ack
    volumes:
      - dbdata:/data/db
    restart: unless-stopped
    networks:
      - app-network
  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - "REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL"
    command:
      - redis-server
      - "--bind"
      - redis
      - "--port"
      - "6379"
    volumes:
      - "redis_data:/usr/local/etc/redis/redis.conf"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  dbdata:
  redis_data:
